### PR TITLE
14 set up automated conda release

### PR DESCRIPTION
**Pull request by bschroeter**
Working on the automated release strategy for the client to conda.

I have taken inspiration from the benchcab workflow. It can't be fully tested until a release is triggered, but it would be good to have someone cast an eye over the configs before I start testing the publish.

### CODE REVIEW

**Comment by SeanBryan51** [comment]
You can test out the conda publish action by triggering the action in a fork of meorg_client. I remember testing the benchcab continuous deployment in a fork and uploaded the package to my personal anaconda profile to check things were working.

**Comment by bschroeter** [comment]
> You can test out the conda publish action by triggering the action in a fork of meorg_client. I remember testing the benchcab continuous deployment in a fork and uploaded the package to my personal anaconda profile to check things were working.
> 
> Here is the relevant pull request for benchcab: [CABLE-LSM/benchcab#89](https://github.com/CABLE-LSM/benchcab/pull/89)

Thanks @SeanBryan51, I'll give that a go

**Comment by bschroeter** [comment]
@SeanBryan51 , looks like the upload to my personal profile worked. It has highlighted a couple of missing dependencies in the configs. I will re-assign the PR once I have that worked out

**Comment by bschroeter** [comment]
Closing in favour of https://github.com/CABLE-LSM/meorg_client/pull/37

**Pull request closed without merging**
